# Handling Errors with try and catch
```javascript
try {
    test();
} catch (error) {
    console.log(error);
} finally {
    console.log('Finally!');
}
```